**Import Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [2]:
cd C:\Users\kandr\Desktop\FALL 21\F1-Information Security Analysis and Audit\ISAA Lab-2

C:\Users\kandr\Desktop\FALL 21\F1-Information Security Analysis and Audit\ISAA Lab-2


In [6]:
dataset = pd.read_csv('Malware dataset.csv')
dataset2 = dataset.copy()
dataset2 = dataset.drop(['classification'], axis=1)

X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 2].values
print (X)

[[   0    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [ 997 4096    0 ...    0    0    0]
 [ 998 4096    0 ...    0    0    0]
 [ 999 4096    0 ...    0    0    0]]


**label Encoding**

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print (y)

[1 1 1 ... 1 1 1]


**Splitting the dataset into the Training set and Test set**

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [9]:
print(X_train)

[[  606 12288     0 ...    10     0     0]
 [  228 28672     0 ...     0     0     0]
 [  382  4096     0 ...     1     0     0]
 ...
 [  613 12288     0 ...    11     0     0]
 [  567  4096     0 ...     2     0     0]
 [  268     0     0 ...     0     0     0]]


In [10]:
print(y_train)

[0 1 0 ... 0 0 1]


In [11]:
print(X_test)

[[    582       0       0 ...       8       0       0]
 [    498       0       0 ...       0       0       0]
 [    227 1028096       0 ...       4       0       0]
 ...
 [    585    4096       0 ...       0       0       0]
 [    519       0       0 ...       7       0       0]
 [    831       0       0 ...       0       0       0]]


In [12]:
print(y_test)

[1 0 0 ... 1 0 0]


**Feature Scaling**

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[ 0.36731703 -0.15969785  0.         ...  2.5559669   0.
   0.        ]
 [-0.941068   -0.14179605  0.         ... -0.50896701  0.
   0.        ]
 [-0.40802225 -0.16864875  0.         ... -0.20247362  0.
   0.        ]
 ...
 [ 0.39154638 -0.15969785  0.         ...  2.8624603   0.
   0.        ]
 [ 0.23232492 -0.16864875  0.         ...  0.10401977  0.
   0.        ]
 [-0.80261455 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


In [15]:
print(X_test)

[[ 0.28424496 -0.1731242   0.         ...  1.94298012  0.
   0.        ]
 [-0.00650727 -0.1731242   0.         ... -0.50896701  0.
   0.        ]
 [-0.94452933  0.95021383  0.         ...  0.71700655  0.
   0.        ]
 ...
 [ 0.29462897 -0.16864875  0.         ... -0.50896701  0.
   0.        ]
 [ 0.06618079 -0.1731242   0.         ...  1.63648673  0.
   0.        ]
 [ 1.14611763 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


**Training Model on the Training set**

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\kandr\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

**Predicting the Test set results**

In [18]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


**Confusion Matrix and Accuracy**

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11590   938]
 [  560 11912]]


0.94008

In [20]:
import sklearn.metrics as metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.94008
Precision: 0.9270038910505837
Recall: 0.9550994227068633
